### ISSUE TITLE
H5移动端按钮相关 

### ISSUE THREAD

**Issue by t61649314** [t61649314/my-h5-note#11]
### 想要增加移动端touch效果可以通过伪类:active来完成，前提是页面引入了zepto或者增加一句代码：
```javascript
document.body.addEventListener('touchstart', function () { });
```

### 去除android a/button/input标签被点击时产生的边框 以及去除ios a标签被点击时产生的半透明灰色背景
```css
-webkit-tap-highlight-color: rgba(255, 0, 0, 0);
```

### 一个效果还可以的按钮点击交互，黑色的透明遮蔽层
```css
.btn {
    position: relative;
}

.btn:active:after {
    opacity: 0.4;
}

.btn:after {
    background-color: #000;
    content: " ";
    opacity: 0;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    position: absolute;
}
```
