### ISSUE TITLE
移动端、webkit相关常用css整理

### ISSUE THREAD

**Issue by t61649314** [t61649314/my-h5-note#8]
### webkit scroll
+ 滑动惯性
+ 触底反弹
+ 更流畅
+ 解决X轴Y轴可以同时滚动时，无法让滚动事件冒泡的BUG
+ IOS13之后滚动区域默认都会自带不需要单独添加

```css
-webkit-overflow-scrolling: touch;
```

### 字体抗锯齿渲染
```css
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

### 去除移动端长按选取，同时排除input
```css
user-select: none;
input {
    -webkit-user-select: auto;
}
```
### 移除wk内核默认滚动条样式
```css
::-webkit-scrollbar {
    display: none;
}
```
