### ISSUE TITLE
Iphone-XR，XS，XS MAX 系列适配

### ISSUE THREAD

**Issue by t61649314** [t61649314/my-h5-note#9]
### 安全区域
适配的核心目的就是尽量把我们的页面布局放在安全区域
使用viewport-fit=cover让我们可以使用constant函数
```css
//body部分尽量在安全区域中
body {
    padding-top: constant(safe-area-inset-top);   //为导航栏+状态栏的高度 88px            
    padding-left: constant(safe-area-inset-left);   //如果未竖屏时为0                
    padding-right: constant(safe-area-inset-right); //如果未竖屏时为0                
    padding-bottom: constant(safe-area-inset-bottom);//为底下圆弧的高度 34px       
}

//吸底部分避开非安全距离
{
    bottom: constant(safe-area-inset-bottom) !important;
    bottom: env(safe-area-inset-bottom) !important;
}

```

### 媒体查询
iPhone XR：
```css
/* 1792x828px at 326ppi */
@media only screen 
    and (device-width : 414px) 
    and (device-height : 896px) 
    and (-webkit-device-pixel-ratio : 2) { }
```
iPhone XS、X
```css
/* 2436x1125px at 458ppi */
@media only screen 
    and (device-width : 375px) 
    and (device-height : 812px) 
    and (-webkit-device-pixel-ratio : 3) { }
```
iPhone XS Max
```css
/* 2688x1242px at 458ppi */
@media only screen 
    and (device-width : 414px) 
    and (device-height : 896px) 
    and (-webkit-device-pixel-ratio : 3) { }
```

### 自用css
```css
//iphonex适配
//当 viewport-fit=contain 时 constant 函数是不起作用的，必须要配合 viewport-fit=cover 使用。对于不支持 constant 的浏览器，浏览器将会忽略它。
//官方文档中提到 env 函数即将要替换 constant 函数，暂时都写上去。
@media only screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) {
    //body四周安全区域处理
    body {
        padding: constant(safe-area-inset-top) constant(safe-area-inset-right) constant(safe-area-inset-bottom) constant(safe-area-inset-left);
        padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
    }

    //吸底的fixed元素可以带上这个class来脱离iphonex非安全区域
    .fixed-bottom-X {
        bottom: constant(safe-area-inset-bottom) !important;
        bottom: env(safe-area-inset-bottom) !important;
    }
}
```

### 参考资料
[https://www.cnblogs.com/lolDragon/p/7795174.html](https://www.cnblogs.com/lolDragon/p/7795174.html)
[https://blog.csdn.net/qq_27080247/article/details/78665450](https://blog.csdn.net/qq_27080247/article/details/78665450)
